### PR TITLE
Update index.html

### LINKED ISSUE #13: Fix preview
@pkra You made a commit 'Fix preview', but now it seems to be broken =D

### PR DESCRIPTION
**Pull request by pkra**
Fix #13

### CODE REVIEW

**Comment by drlippman** [comment]
Out of pure curiosity, why can't the setup be in a separate script?  Or did it just need to not be at the bottom of the page?

**Comment by drlippman** [comment]
Hmm..  This still doesn't seem to be working.  I suppose I should be checking these before merging them ;)

**Comment by pkra** [comment]
> why can't the setup be in a separate script? Or did it just need to not be at the bottom of the page?

The configuration needs to load before MathJax. Since I'm using the plain JS style configuration, loading it after MathJax overwrites the global MathJax variable, breaking everything. Sorry about not finishing up my PR back in August.

Personally, I don't have a problem with inlining a small script for a demo site like this. If people do, then we can move back to using a separate script and inject MathJax.js from that script.

**Comment by pkra** [comment]
> Hmm.. This still doesn't seem to be working. I suppose I should be checking these before merging them ;)


It takes a while for gh-pages do be updated. It works for me now.

**Comment by drlippman** [comment]
For me, inspection is showing the pages have updated, but the rendering isn't updating when I change the input text.  Have tried in both FF and Chrome. 


     On Friday, November 13, 2015 1:31 AM, Peter Krautzberger <notifications@github.com> wrote:
   

 
Hmm.. This still doesn't seem to be working. I suppose I should be checking these before merging them ;)
It takes a while for gh-pages do be updated. It works for me now.—

**Comment by pkra** [comment]
Does it help to wait for a bit before typing something? (Especially, wait for the fastPreview to be replaced.)

**Comment by drlippman** [comment]
Ahh, there it goes.  The CDN was just running really slow, so it never got past fastPreview earlier. 


     On Friday, November 13, 2015 1:35 AM, Peter Krautzberger <notifications@github.com> wrote:
   

 Does it help to wait for a bit before typing something? (Especially, wait for the fastPreview to be replaced.)—

**Comment by pkra** [comment]
Should we disable the Fast Preview? It's probably not worth it with one equation.

**Comment by adius** [comment]
I think we should disable fast preview. Looks more like a bug ^^

**Pull request merged**
